### ISSUE TITLE
convert integer to datetime bug, Python int too large to convert to C long

### ISSUE THREAD

**Issue by poc7667** [pydata/pandas#10987]
# pandas version `pandas (0.16.1)`

    for field in ["release_date", "date"]:
        if field in df:
            df[field] = pd.to_datetime(df[field], unit="ms")

![](https://i.imgur.com/GnNoqY7.png)

**Comment by jorisvandenbossche** [comment]
Which version are you using?

```
In [30]: pd.to_datetime(1430784000000, unit='ms')
Out[30]: Timestamp('2015-05-05 00:00:00')

In [31]: pd.__version__
Out[31]: '0.16.2'
```

**Comment by jorisvandenbossche** [comment]
Sorry, you did specify the version. Can you give a reprodicible example? (make up some dummy data that gives you this error) 
For a small example (see above), it works for me on 0.16.2

**Comment by jreback** [comment]
ok on 0.16.1 as well.



```
In [1]: pd.to_datetime(1430784000000, unit='ms')
Out[1]: Timestamp('2015-05-05 00:00:00')

In [2]: pd.__version__
Out[2]: '0.16.1'
```

You get this error if the unit you pass is incompatible
```
In [4]: pd.to_datetime(1430784000000, unit='s')
OverflowError: Python int too large to convert to C long
```

**Comment by wmacmillan** [comment]
Just to clarify on @jreback's point here, if the time since epoch is recorded in milliseconds, and you select seconds as your unit, you get this _very_ unhelpful error.

**Comment by jreback** [comment]
yeah, we should prob just catch this and re-raise as a more helpful error message. Want to do a PR?

**Comment by libelo** [comment]
Here is the error message i got when i tried to regenerate this issue. It looks like it already has been solved. Should we close this issue?

```
In [1]: pd.to_datetime(1430784000000, unit='s')
Out[1]: OutOfBoundsDatetime: cannot convert input with unit 's'

In [2]: pd.__version__
Out[2]: '0.18.1'
```

**Comment by jreback** [comment]
yes, a number of issues have touched on this recently. I don't think any more tests are necessary.

closing as fixed.

**Comment by jorisvandenbossche** [comment]
Tests were added here: https://github.com/pydata/pandas/pull/13183/files

**Comment by melzoghbi** [comment]
I have pandas version 0.19.2 and i still get this error when using to_datetime() method. My column type is int64 and i still get errors or no conversion.

Check this issue post: #13183 

Thanks.

**Comment by hashamMunir** [comment]
OutOfBoundsDatetime: cannot convert input with unit 's'
issue in
print(pd.__version__)
0.23.3
I have pd df containing the dates in unix timestamp.

**Comment by vaibhavjaitly** [comment]
# Changing the timestamp column to datatime type to help in the day to day trend analysis

#Time = data['timestamp'] 
x = datetime(20160301103842, 'Y%m%d%H%M%S')
x

OverflowError: Python int too large to convert to C lon
